java:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - 3.0
build:
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pshort
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=5.0.0
      cassandra.directory=/home/jenkins/bdp
      dse=true
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
